package zed.rainxch.core.presentation.theme

import androidx.compose.ui.graphics.Color

data class StatusColors(
    val freshnessHot: Color,
    val freshnessFresh: Color,
    val freshnessWarm: Color,
    val freshnessCool: Color,
    val freshnessDormant: Color,
    val waxIntact: Color,
    val waxCracked: Color,
    val waxOpen: Color,
    val permLow: Color,
    val permModerate: Color,
    val permHigh: Color,
    val trendRising: Color,
    val trendFlat: Color,
    val trendFalling: Color,
    val starActive: Color,
    val issueOpen: Color,
    val issueClosed: Color,
    val pullOpen: Color,
    val pullMerged: Color,
    val pullClosed: Color,
    val severityCritical: Color,
    val severityHigh: Color,
    val severityMedium: Color,
    val severityLow: Color,
    val severityUnknown: Color,
    val statusReady: Color,
    val statusWarning: Color,
    val statusError: Color,
    val protectionSignature: Color,
    val protectionPrivileged: Color,
)
